""" Global app settings.
"""

RESIZE_CONTAINER_DEFAULT_WIDTH = 300
RESIZE_CONTAINER_DEFAULT_HEIGHT = 300
RESIZE_BOX_WIDTH = 10
RESIZE_BOX_HEIGHT = 10
RESIZE_BOX_LINE_WIDTH = 2
RESIZE_BOX_PLUS_LENGTH = 10
RESIZE_BOX_PLUS_PADDING = 3
RESIZE_MIN_WIDTH = 250
RESIZE_MIN_HEIGHT = 250
