'''
Created on Mar 10, 2014

@author: vagrant
'''
RESIZE_CONTAINER_DEFAULT_WIDTH = 300
RESIZE_CONTAINER_DEFAULT_HEIGHT = 300
RESIZE_BOX_WIDTH = 16
RESIZE_BOX_HEIGHT = 16
RESIZE_BOX_LINE_WIDTH = 2
RESIZE_BOX_PLUS_LENGTH = 10
RESIZE_BOX_PLUS_PADDING = 3
